CREATE TABLE Queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    queue_number INT NOT NULL,
    ph_num VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    attempts INT NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'waiting' CHECK(status IN ('waiting', 'serving', 'done')),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP UNIQUE
);

CREATE TABLE Prizes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    sector VARCHAR(20) NOT NULL DEFAULT 'software',
    points INT NOT NULL,
    quantity_left INT NOT NULL DEFAULT -1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GamePrices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_name VARCHAR(255) NOT NULL,
    price VARCHAR(50) NOT NULL,
    sector VARCHAR(20) NOT NULL DEFAULT 'software',
    unit VARCHAR(50) NOT NULL DEFAULT 'attempt',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);